### ISSUE TITLE
違いが分かりません。

### ISSUE THREAD

**Issue by c0a2104665** [c0a21056/ProjExD#15]
https://github.com/c0a21056/ProjExD/blob/bf983abaad53bf906311bd2274b206f994780ac2/ex02/calc.py#L57
どのような実行を行っているのかわかりにくいため、詳しく説明があった方が分かりやすいと思いました。

**Comment by c0a21056** [comment]
if文を＝ボタンだけ背景の色を変えようとしていたんですができずに背景の色を変更するのを諦めたんですがプログラムを消すのを忘れていました
