### ISSUE TITLE
回数について

### ISSUE THREAD

**Issue by SawaiMasaki** [c0a21056/ProjExD#5]
https://github.com/c0a21056/ProjExD/blob/27c2ccd0f4d9fc0e677fbc1e8fdccb8a90d1ce1e/Ex01/alphabet.py#L36
試行回数が増えた場合どうするのか

**Comment by c0a21056** [comment]
for文を使用して試行回数が増えた場合に対応しようとしたのですがうまくプログラムを作成できずこのような形になりました
