### ISSUE TITLE
コードについて

### ISSUE THREAD

**Issue by C0A21122** [c0a21056/ProjExD#6]
https://github.com/c0a21056/ProjExD/blob/27c2ccd0f4d9fc0e677fbc1e8fdccb8a90d1ce1e/Ex01/alphabet.py#L11
関数で何が行われるか分かる関数名だといいですね。
わかりやすいコードだとは思います！

**Comment by c0a21056** [comment]
文字の表示の部分なので def mozi(): に関数名を変更しました
